### ISSUE TITLE
Orange links in page listview

### ISSUE THREAD

**Issue by Aybee** [contaoacademy/contao-videohandbuch#3]
Hallo Christian,
die Erweiterung macht die Seitennamen in der Pagelistview orange.
https://github.com/contaoacademy/contao-videohandbuch/blob/master/assets/academy.css#L16-L18

Kannst du in der Online-Demo ausprobieren. Die CSS-Regel mit den Browser-Devtools einfügen. Ist bei mir in ner 4.13.23 genauso wie in der Demo 5.1.6.

**Comment by contaoacademy** [comment]
Danke, ist mit Version `1.3.1` behoben.
